### ISSUE TITLE
bundler error when launching from docker-compose

### ISSUE THREAD

**Issue by rsanath** [up-for-grabs/up-for-grabs.net#1318]
I'm unable to start the project locally using Docker.
The build succeeds but throws this error

```
Starting up-for-grabsnet_app_1 ... done
Attaching to up-for-grabsnet_app_1
app_1  | /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:313:in `check_for_activated_spec!': You have already activated ffi 1.11.1, but your Gemfile requires ffi 1.10.0. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
app_1  |        from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:31:in `block in setup'
app_1  |        from /usr/local/lib/ruby/2.5.0/forwardable.rb:229:in `each'
app_1  |        from /usr/local/lib/ruby/2.5.0/forwardable.rb:229:in `each'
app_1  |        from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:26:in `map'
app_1  |        from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:26:in `setup'
app_1  |        from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler.rb:107:in `setup'
app_1  |        from /usr/local/bundle/gems/jekyll-3.8.5/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
app_1  |        from /usr/local/bundle/gems/jekyll-3.8.5/exe/jekyll:11:in `<top (required)>'
app_1  |        from /usr/local/bundle/bin/jekyll:23:in `load'
app_1  |        from /usr/local/bundle/bin/jekyll:23:in `<main>'
up-for-grabsnet_app_1 exited with code 1
```

I'm not an expert at this but I was able to get it run by regenerating the `Gemfile.lock`.
Is deleting the `Gemfile.lock` the solution? or should something be fixed elsewhere?

PS. I couldn't test it without Docker as there are lots of version conflicts with the ruby in my system.

**Comment by shiftkey** [comment]
> I'm unable to start the project locally using Docker.

Can you walk me through the steps you're performing here? This will help me better understand what you're trying to achieve.

> I'm not an expert at this but I was able to get it run by regenerating the `Gemfile.lock`.
> Is deleting the `Gemfile.lock` the solution? or should something be fixed elsewhere?

Can you share what the diff is between your new lockfile and the one we have in version control? I don't think we add the lockfile to the docker container, and we [test `docker build` as part of each CI build](https://travis-ci.org/up-for-grabs/up-for-grabs.net/builds/574550368#L748), but maybe we've overlooked something?

> PS. I couldn't test it without Docker as there are lots of version conflicts with the ruby in my system.

I've had more success with prepending `bundle exec` to the commands I was running, e.g. `bundle exec jekyll serve`, to workaround these sorts of issues.

**Comment by rsanath** [comment]
I cloned the project and just executed the command
 
`docker-compose up --build`

here is the entire log for that command if that may help you 

```
$ docker-compose up --build
Building app
Step 1/3 : FROM starefossen/github-pages:onbuild
# Executing 1 build trigger
 ---> 3d5b4daad382
Step 2/3 : RUN apk update && apk add libc-dev gcc g++ make
 ---> Running in 6a04b137364f
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
v3.7.3-128-g9490e53a0c [http://dl-cdn.alpinelinux.org/alpine/v3.7/main]
v3.7.3-78-g634dbf6dd0 [http://dl-cdn.alpinelinux.org/alpine/v3.7/community]
OK: 9062 distinct packages available
(1/15) Upgrading musl (1.1.18-r3 -> 1.1.18-r4)
(2/15) Installing binutils-libs (2.30-r2)
(3/15) Installing binutils (2.30-r2)
(4/15) Installing gmp (6.1.2-r1)
(5/15) Installing isl (0.18-r0)
(6/15) Installing libgomp (6.4.0-r5)
(7/15) Installing libatomic (6.4.0-r5)
(8/15) Installing mpfr3 (3.1.5-r1)
(9/15) Installing mpc1 (1.0.3-r1)
(10/15) Installing gcc (6.4.0-r5)
(11/15) Installing musl-dev (1.1.18-r4)
(12/15) Installing libc-dev (0.7.1-r0)
(13/15) Installing g++ (6.4.0-r5)
(14/15) Upgrading musl-utils (1.1.18-r3 -> 1.1.18-r4)
(15/15) Installing make (4.2.1-r0)
Executing busybox-1.27.2-r11.trigger
OK: 200 MiB in 51 packages
Removing intermediate container 6a04b137364f
 ---> e35b016d218a
Step 3/3 : RUN bundle install
 ---> Running in baff2c454f86
Fetching gem metadata from https://rubygems.org/...........
Using concurrent-ruby 1.1.5
Using i18n 0.9.5
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Fetching activesupport 4.2.11.1
Installing activesupport 4.2.11.1
Fetching public_suffix 3.0.3
Installing public_suffix 3.0.3
Using addressable 2.6.0
Using bundler 1.16.3
Using coffee-script-source 1.11.1
Using execjs 2.7.0
Using coffee-script 2.4.1
Using colorator 1.1.0
Using ruby-enum 0.7.2
Using commonmarker 0.17.13
Using dnsruby 1.61.2
Using eventmachine 1.2.7
Using http_parser.rb 0.6.0
Using em-websocket 0.5.1
Fetching ffi 1.10.0
Installing ffi 1.10.0 with native extensions
Using ethon 0.12.0
Fetching multipart-post 2.0.0
Installing multipart-post 2.0.0
Using faraday 0.15.4
Using forwardable-extended 2.6.0
Using gemoji 3.0.1
Using sawyer 0.8.2
Using octokit 4.14.0
Using typhoeus 1.3.1
Fetching github-pages-health-check 1.16.1
Installing github-pages-health-check 1.16.1
Using rb-fsevent 0.10.3
Using rb-inotify 0.10.0
Using sass-listen 4.0.0
Using sass 3.7.4
Using jekyll-sass-converter 1.5.2
Using ruby_dep 1.5.0
Using listen 3.1.5
Using jekyll-watch 2.2.1
Using kramdown 1.17.0
Using liquid 4.0.0
Using mercenary 0.3.6
Using pathutil 0.16.2
Using rouge 2.2.1
Using safe_yaml 1.0.5
Fetching jekyll 3.8.5
Installing jekyll 3.8.5
Using jekyll-avatar 0.6.0
Using jekyll-coffeescript 1.1.1
Using jekyll-commonmark 1.3.1
Using jekyll-commonmark-ghpages 0.1.5
Using jekyll-default-layout 0.1.4
Fetching jekyll-feed 0.11.0
Installing jekyll-feed 0.11.0
Using jekyll-gist 1.5.0
Using jekyll-github-metadata 2.12.1
Using mini_portile2 2.4.0
Fetching nokogiri 1.10.4
Installing nokogiri 1.10.4 with native extensions
Using html-pipeline 2.11.0
Using jekyll-mentions 1.4.1
Using jekyll-optional-front-matter 0.3.0
Using jekyll-paginate 1.1.0
Using jekyll-readme-index 0.2.0
Using jekyll-redirect-from 0.14.0
Fetching jekyll-relative-links 0.6.0
Installing jekyll-relative-links 0.6.0
Fetching rubyzip 1.2.2
Installing rubyzip 1.2.2
Using jekyll-remote-theme 0.3.1
Using jekyll-seo-tag 2.5.0
Using jekyll-sitemap 1.2.0
Using jekyll-swiss 0.4.0
Using jekyll-theme-architect 0.1.1
Using jekyll-theme-cayman 0.1.1
Using jekyll-theme-dinky 0.1.1
Using jekyll-theme-hacker 0.1.1
Using jekyll-theme-leap-day 0.1.1
Using jekyll-theme-merlot 0.1.1
Using jekyll-theme-midnight 0.1.1
Using jekyll-theme-minimal 0.1.1
Using jekyll-theme-modernist 0.1.1
Using jekyll-theme-primer 0.5.3
Using jekyll-theme-slate 0.1.1
Using jekyll-theme-tactile 0.1.1
Using jekyll-theme-time-machine 0.1.1
Using jekyll-titles-from-headings 0.5.1
Fetching jemoji 0.10.2
Installing jemoji 0.10.2
Using minima 2.5.0
Fetching unicode-display_width 1.5.0
Installing unicode-display_width 1.5.0
Using terminal-table 1.8.0
Fetching github-pages 198
Installing github-pages 198
Bundle complete! 1 Gemfile dependency, 85 gems now installed.
Bundled gems are installed into `/usr/local/bundle`
Removing intermediate container baff2c454f86
 ---> d007fabd0998
Successfully built d007fabd0998
Successfully tagged up-for-grabsnet_app:latest
Recreating up-for-grabsnet_app_1 ... done
Attaching to up-for-grabsnet_app_1
app_1  | /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:313:in `check_for_activated_spec!': You have already activated ffi 1.11.1, but your Gemfile requires ffi 1.10.0. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
app_1  |        from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:31:in `block in setup'
app_1  |        from /usr/local/lib/ruby/2.5.0/forwardable.rb:229:in `each'
app_1  |        from /usr/local/lib/ruby/2.5.0/forwardable.rb:229:in `each'
app_1  |        from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:26:in `map'
app_1  |        from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:26:in `setup'
app_1  |        from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler.rb:107:in `setup'
app_1  |        from /usr/local/bundle/gems/jekyll-3.8.5/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
app_1  |        from /usr/local/bundle/gems/jekyll-3.8.5/exe/jekyll:11:in `<top (required)>'
app_1  |        from /usr/local/bundle/bin/jekyll:23:in `load'
app_1  |        from /usr/local/bundle/bin/jekyll:23:in `<main>'
up-for-grabsnet_app_1 exited with code 1
```
