### ISSUE TITLE
Issue Building on Fedora

### ISSUE THREAD

**Issue by JiveyGuy** [up-for-grabs/up-for-grabs.net#3645]
I had this error when building: 

```
up-for-grabs.net on  gh-pages [!] is 📦 v1.0.0 via  v16.18.1 via 💎 v3.0.4 took 13s 
❯ bundle exec jekyll serve
Configuration file: /home/jivey/devel/github/up-for-grabs.net/_config.yml
            Source: /home/jivey/devel/github/up-for-grabs.net
       Destination: /home/jivey/devel/github/up-for-grabs.net/_site
      Generating... 
Error reading file /home/jivey/devel/github/up-for-grabs.net/_layouts/default.html: no implicit conversion of Hash into Integer 
Error reading file /home/jivey/devel/github/up-for-grabs.net/index.html: no implicit conversion of Hash into Integer 
Error reading file /home/jivey/devel/github/up-for-grabs.net/javascripts/projects.json: no implicit conversion of Hash into Integer 
jekyll 2.4.0 | Error:  undefined method `escape' for URI:Module
/home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/gems/jekyll-2.4.0/lib/jekyll/url.rb:92:in `escape_path': undefined method `escape' for URI:Module (NoMethodError)
	from /home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/gems/jekyll-2.4.0/lib/jekyll/url.rb:49:in `block in generate_url'
	from /home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/gems/jekyll-2.4.0/lib/jekyll/url.rb:48:in `each'
	from /home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/gems/jekyll-2.4.0/lib/jekyll/url.rb:48:in `inject'
	from /home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/gems/jekyll-2.4.0/lib/jekyll/url.rb:48:in `generate_url'
	from /home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/gems/jekyll-2.4.0/lib/jekyll/url.rb:40:in `to_s'
	from /home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/gems/jekyll-2.4.0/lib/jekyll/page.rb:87:in `url'
	from /home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:352:in `block in site_payload'
	from /home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:352:in `select'
	from /home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:352:in `site_payload'
	from /home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:267:in `render'
	from /home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:46:in `process'
	from /home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/gems/jekyll-2.4.0/lib/jekyll/command.rb:28:in `process_site'
	from /home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:55:in `build'
	from /home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:33:in `process'
	from /home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/gems/jekyll-2.4.0/lib/jekyll/commands/serve.rb:25:in `block (2 levels) in init_with_program'
	from /home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/gems/jekyll-2.4.0/bin/jekyll:18:in `<top (required)>'
	from /home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/bin/jekyll:25:in `load'
	from /home/jivey/devel/github/up-for-grabs.net/vendor/bundle/ruby/3.0.0/bin/jekyll:25:in `<top (required)>'
	from /home/jivey/.local/share/gem/ruby/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `load'
	from /home/jivey/.local/share/gem/ruby/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /home/jivey/.local/share/gem/ruby/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:23:in `run'
	from /home/jivey/.local/share/gem/ruby/gems/bundler-2.3.7/lib/bundler/cli.rb:484:in `exec'
	from /home/jivey/.local/share/gem/ruby/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/jivey/.local/share/gem/ruby/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/jivey/.local/share/gem/ruby/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /home/jivey/.local/share/gem/ruby/gems/bundler-2.3.7/lib/bundler/cli.rb:31:in `dispatch'
	from /home/jivey/.local/share/gem/ruby/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /home/jivey/.local/share/gem/ruby/gems/bundler-2.3.7/lib/bundler/cli.rb:25:in `start'
	from /home/jivey/.local/share/gem/ruby/gems/bundler-2.3.7/exe/bundle:48:in `block in <top (required)>'
	from /home/jivey/.local/share/gem/ruby/gems/bundler-2.3.7/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /home/jivey/.local/share/gem/ruby/gems/bundler-2.3.7/exe/bundle:36:in `<top (required)>'
	from /usr/bin/bundle:23:in `load'
	from /usr/bin/bundle:23:in `<main>'
```
I am using the latest versions of the prerequisites `dnf` has. Is this an error with my configuration or the code?

**Comment by DebayanSen96** [comment]
It seems that you have encountered several errors while trying to build your Jekyll site.

Error reading file /home/jivey/devel/github/up-for-grabs.net/_layouts/default.html: no implicit conversion of Hash into Integer
This error message suggests that there is a problem with the _layouts/default.html file. It's possible that the YAML front matter at the top of the file is malformed or that there is some other syntax error in the file.

Error reading file /home/jivey/devel/github/up-for-grabs.net/index.html: no implicit conversion of Hash into Integer
This error message suggests that there is a problem with the index.html file. Similar to the previous error, it's possible that the YAML front matter is malformed or that there is some other syntax error in the file.

Error reading file /home/jivey/devel/github/up-for-grabs.net/javascripts/projects.json: no implicit conversion of Hash into Integer
This error message suggests that there is a problem with the projects.json file. It's possible that the file is not well-formed JSON or that there is some other syntax error in the file.

jekyll 2.4.0 | Error: undefined method escape' for URI:ModuleThis error message suggests that there is an issue with theURImodule. It's possible that the version of theURI` module being used is not compatible with the version of Jekyll that you are using.

To fix these issues, you can try the following steps:

Check the YAML front matter in the _layouts/default.html and index.html files. Make sure that it is well-formed and does not contain any syntax errors.
Check the syntax of the projects.json file. Make sure that it is well-formed JSON and does not contain any syntax errors.
Update the version of the URI module being used to a compatible version with your version of Jekyll.
Upgrade to the latest version of Jekyll to ensure compatibility with other dependencies. You can do this by running gem update jekyll in your command line interface.

**Comment by shiftkey** [comment]
Closing this out because we're now on Jekyll 4.3.2, and this issue was for Jekyll 2.4. We're also now on Ruby 3.2 so please ensure you're on that version too...
