### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by waldyrious** [up-for-grabs/up-for-grabs.net#594]
On Firefox 50.0.2:

```
TypeError: projectName.toLowerCase is not a function
	TagBuilder/this.addTag http://up-for-grabs.net/javascripts/projectsService.js:50:32
	extractTags/</< http://up-for-grabs.net/javascripts/projectsService.js:73:9
	forEach self-hosted:251:13
	j.forEach https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.2/underscore-min.js:5:597
	extractTags/< http://up-for-grabs.net/javascripts/projectsService.js:72:7
	forEach self-hosted:251:13
	j.forEach https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.2/underscore-min.js:5:597
	extractTags http://up-for-grabs.net/javascripts/projectsService.js:71:5
	extractProjectsAndTags http://up-for-grabs.net/javascripts/projectsService.js:84:15
	ProjectsService http://up-for-grabs.net/javascripts/projectsService.js:89:25
	<anonymous> http://up-for-grabs.net/javascripts/main.js:3:21
	<anonymous> http://up-for-grabs.net/javascripts/main.js:1:2
```
        
On Chrome 57.0.2987.133:

```
Uncaught TypeError: projectName.toLowerCase is not a function
    at TagBuilder.addTag (http://up-for-grabs.net/javascripts/projectsService.js:50:44)
    at http://up-for-grabs.net/javascripts/projectsService.js:73:20
    at Array.forEach (native)
    at Function.j.each.j.forEach (https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.2/underscore-min.js:5:599)
    at http://up-for-grabs.net/javascripts/projectsService.js:72:9
    at Array.forEach (native)
    at Function.j.each.j.forEach (https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.2/underscore-min.js:5:599)
    at extractTags (http://up-for-grabs.net/javascripts/projectsService.js:71:7)
    at extractProjectsAndTags (http://up-for-grabs.net/javascripts/projectsService.js:84:15)
    at new ProjectsService (http://up-for-grabs.net/javascripts/projectsService.js:89:25)
```

**Comment by shiftkey** [comment]
Looks like I probably should have tested #534 better before merging.
